[package]
name = "sign-xpi"
version = "0.1.0"
authors = ["Ethan Glasser-Camp <eglassercamp@mozilla.com>"]

[dependencies]
rusoto = {git = "https://github.com/rusoto/rusoto.git", features = ["s3"]}
rust-apex = "0.2"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
